export const EMPLOYEE_STATUSES = [
  { id: 1, name: "Active", color: "green.300" },
  { id: 2, name: "Inactive", color: "red.300" },
  // Ajoutez d'autres statuts si nécessaire
];

export const EMPLOYEES = [
  {
      id_employe: 1,
      nom: "John",
      prenom: "Doe",
      date_naissance: "1990-05-15",
      age: 34,
      genre: "Masculin",
      situation_matrimoniale: "Célibataire",
      contact_personnel: "123-456-7890",
      email: "john.doe@example.com",
      poste: { titre_poste: "Software Engineer" },
      statut: { id: 1, name: "Active", color: "green.300" },
      affectation: { lieu_affectation: "Bureau Principal" },
      startDate: new Date("2023-01-01"),
      notes: "Good performance.",
  },
  {
      id_employe: 2,
      nom: "Jane",
      prenom: "Smith",
      date_naissance: "1985-11-20",
      age: 38,
      genre: "Féminin",
      situation_matrimoniale: "Mariée",
      contact_personnel: "234-567-8901",
      email: "jane.smith@example.com",
      poste: { titre_poste: "Project Manager" },
      statut: { id: 1, name: "Active", color: "green.300" },
      affectation: { lieu_affectation: "Bureau Principal" },
      startDate: new Date("2022-05-15"),
      notes: "Excellent leadership skills.",
  },
  {
      id_employe: 3,
      nom: "Alice",
      prenom: "Johnson",
      date_naissance: "1992-03-10",
      age: 32,
      genre: "Féminin",
      situation_matrimoniale: "Célibataire",
      contact_personnel: "345-678-9012",
      email: "alice.johnson@example.com",
      poste: { titre_poste: "UX Designer" },
      statut: { id: 2, name: "Inactive", color: "red.300" },
      affectation: { lieu_affectation: "Télétravail" },
      startDate: new Date("2021-08-20"),
      notes: "On leave for further studies.",
  },
  {
      id_employe: 4,
      nom: "Bob",
      prenom: "Brown",
      date_naissance: "1988-02-25",
      age: 36,
      genre: "Masculin",
      situation_matrimoniale: "Célibataire",
      contact_personnel: "456-789-0123",
      email: "bob.brown@example.com",
      poste: { titre_poste: "Data Analyst" },
      statut: { id: 1, name: "Active", color: "green.300" },
      affectation: { lieu_affectation: "Bureau Secondaire" },
      startDate: new Date("2023-02-10"),
      notes: "Great analytical skills.",
  },
  {
      id_employe: 5,
      nom: "Emily",
      prenom: "Davis",
      date_naissance: "1995-07-30",
      age: 29,
      genre: "Féminin",
      situation_matrimoniale: "Mariée",
      contact_personnel: "567-890-1234",
      email: "emily.davis@example.com",
      poste: { titre_poste: "Marketing Specialist" },
      statut: { id: 1, name: "Active", color: "green.300" },
      affectation: { lieu_affectation: "Bureau Principal" },
      startDate: new Date("2023-03-25"),
      notes: "Creative and proactive.",
  },
  // Ajoutez d'autres employés ici
];

export const employeesES = EMPLOYEES.map(emp => ({
  id: emp.id_employe,
  name: `${emp.nom} ${emp.prenom}`,
  position: emp.poste?.titre_poste,
}));
