export const HISTORIQUE_POSTES = [
    {
        id_historique: 1,
        id_employe: 1,
        nom: "John Doe",
        poste_precedent: "Junior Developer",
        poste_actuel: "Software Engineer",
        date_debut: "2022-06-01",
        date_fin: "2023-01-01",
        motif: "Promotion pour bonne performance",
    },
    {
        id_historique: 2,
        id_employe: 2,
        nom: "Jane Smith",
        poste_precedent: "Assistant Project Manager",
        poste_actuel: "Project Manager",
        date_debut: "2021-03-15",
        date_fin: "2022-05-15",
        motif: "Évolution professionnelle",
    },
    {
        id_historique: 3,
        id_employe: 3,
        nom: "Alice Johnson",
        poste_precedent: "UI Designer",
        poste_actuel: "UX Designer",
        date_debut: "2020-05-10",
        date_fin: "2021-08-20",
        motif: "Changement d'équipe",
    },
    {
        id_historique: 4,
        id_employe: 4,
        nom: "Bob Brown",
        poste_precedent: "Junior Data Analyst",
        poste_actuel: "Data Analyst",
        date_debut: "2022-01-15",
        date_fin: "2023-02-10",
        motif: "Promotion pour contribution significative",
    },
    {
        id_historique: 5,
        id_employe: 5,
        nom: "Emily Davis",
        poste_precedent: "Marketing Assistant",
        poste_actuel: "Marketing Specialist",
        date_debut: "2022-11-20",
        date_fin: "2023-03-25",
        motif: "Reconnaissance de ses compétences créatives",
    },
];
